spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379

  jpa:
    properties:
      hibernate:
        default_schema: auth_service

  flyway:
    schemas: auth_service

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  issuer: ${JWT_ISSUER}
  audiences: ${JWT_AUDIENCES}

app:
  outbox:
    poll-interval-ms: ${POLL_INTERVAL_MS}
    recovery-interval-ms: ${RECOVERY_INTERVAL_MS}

  cookie:
    secure: true
    max-age: ${COOKIE_MAX_AGE}
