spring:
  kafka:
    consumer:
      group-id: billing-service

  jpa:
    properties:
      hibernate:
        default_schema: billing_service

  flyway:
    schemas: billing_service

services:
  core:
    url: ${CORE_URL}
