spring:
  kafka:
    consumer:
      group-id: core-service

  jpa:
    properties:
      hibernate:
        default_schema: core_service

  flyway:
    schemas: core_service

app:
  outbox:
    poll-interval-ms: ${POLL_INTERVAL_MS}
    recovery-interval-ms: ${RECOVERY_INTERVAL_MS}
